#!/bin/bash

if [ "$EUID" -ne 0 ]; then
	echo "please run as root"
	exit
fi

if [ $# != 1 ]; then
	echo "usage: http_add_vhost <vhost>"
	exit 1
fi

VHOST=$1
LOG_DIR="/var/log/apache2/$VHOST"
WWW_DIR="/var/www/$VHOST"
VHOST_FILE="/etc/apache2/sites-available/$VHOST.conf"

if [ -z "$(dig +short $VHOST)" ]; then
	echo "domain doesn't exist"
	exit 1
fi

if [ -e $VHOST_FILE ]; then
	echo "vhost already exists"
	exit 1
fi

mkdir $WWW_DIR

echo "<VirtualHost *:80>
	ServerName $VHOST
	DocumentRoot $WWW_DIR
	ErrorLog /var/www/$VHOST_error.log
	CustomLog /var/www/$VHOST_access.log combined
</VirtualHost>" > $VHOST_FILE

SUBDOMAIN=$(echo $VHOST | grep -oP ".+(?=(\.lennert-verwimp))")
echo "welcome $SUBDOMAIN" > "$WWW_DIR/index.html"

a2ensite $VHOST > /dev/null
systemctl reload apache2
