#!/bin/bash
vhost=$(echo $1 | cut -d'.' -f1)
echo $vhost
domain=$(echo $1 | cut -d'.' -f2-)
echo $domain
if [ "$domain" == "lennert-verwimp.sb.uclllabs.be" ]; then
	if ! [[ "$vhost" =~ [^a-zA-Z0-9]+ ]]; then 
	mkdir -p /var/www/$vhost/public_html
	touch /etc/apache2/sites-available/$vhost.conf
	echo "<VirtualHost *:80>
	    ServerName $vhost.lennert-verwimp.sb.uclllabs.be
            ServerAdmin root@lennert-verwimp
            DocumentRoot /var/www/$vhost.lennert-verwimp.sb.uclllabs.be
            ErrorLog /var/www/$vhost_error.log
            CustomLog /var/www/$vhost.lennert-verwimp.sb.uclllabs.be/requests.log combined
	</VirtualHost>" >> /etc/apache2/sites-available/$vhost.conf

	touch /var/www/$vhost/public_html/index.html
		echo "<html>
		<head>
		<title>Vhost $vhost</title>
		</head>
		<body>
		<p>welcome $vhost</p>
		</body>
		</html>" >> /var/www/$vhost/public_html/index.html

	dns_add_record -t A $vhost 193.191.177.217 $domain
	a2ensite $vhost.conf
	systemctl reload apache2
	else
	echo "invalid vhost name"
	fi
else
echo "invalid domain"
fi
